### ISSUE TITLE
Pod status becomes BackOff and fails to start

### ISSUE THREAD

**Issue by yuzujoe** [aquasecurity/starboard#551]
**What steps did you take and what happened:**

Hi !!

I have been using starboard for container vulnerability scanning on kubernetes.
In that case, it failed to start and I saw the error

```console
E0506 03:15:06.116535       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 593 [running]:
```

**What did you expect to happen:**

This looks like an error on the k8s side, but when I checked to see if there were any other errors, I found that.

```console
"level":"error","ts":1620270905.7972443,"logger":"controller-runtime.manager.controller.job","msg":"Reconciler error","reconciler group":"batch","reconciler kind":"Job","name":"scan-vulnerabilityreport-789f7c5fff","namespace":"starboard-operator","error":"Pod \"<my-pod-name>\" not found","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/runner/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:267\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:235\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.2/pkg/internal/controller/controller.go:198\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185\nk8s.io/apimachinery/pkg/util/wait.UntilWithContext\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:99"}
```

This error is occurring because the Pod in this error is a Cron Job, which doesn't actually exist.
If this Pod is the cause of the error, I would like to ignore it or take some other action.

**Environment:**

- Starboard version : 0.10.1
- Kubernetes version: EKS 1.19 (using helm)

**Comment by yuzujoe** [comment]
If I fix the version of helm chart to 0.5.1, I don't have this problem anymore, although I have another problem

**Comment by danielpacak** [comment]
👋 @yuzujoe What is that another problem that you mentioned?

**Comment by yuzujoe** [comment]
@danielpacak 

Sorry, changed title.
Do you understand what I mean? 🙇‍♂️

> What is that another problem that you mentioned? 

Maybe, I think it's a problem here.
https://github.com/aquasecurity/starboard/issues/518

I thought this problem was fixed in the latest image, is that not the case?
I'm using helm chart version 0.5.1

**Comment by yuzujoe** [comment]
@danielpacak The issue in #518 is not related to this issue, so this issue is closed.
